version: '3.8'

services:

  pgadmin:
    image: dpage/pgadmin4
    container_name: to_do_list_pg_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: asselonay@gmail.com
      PGADMIN_DEFAULT_PASSWORD: sss
    ports:
      - "4444:80"
    networks:
      - my_network

networks:
  my_network:
